### PR TITLE
Fixes vert-x3/vertx-sql-common#14: Support query timeout

### PR DESCRIPTION
**Pull request by pmlopes**
Fixes vert-x3/vertx-sql-common#14

### CODE REVIEW

**Comment by vietj** [comment]
we should try to test this using HSQLDB ability to run java code and that calls a function that does Thread.sleep or something like this.

**Comment by vietj** [comment]
FIY : the build is currently failing in CI because the sql-common was merged

**Comment by pmlopes** [comment]
Test was added and build is fixed

**Comment by vietj** [comment]
great

**Pull request merged**
