### PR TITLE
Fixes vert-x3/vertx-sql-common#19: implement optimistic casting for temporal and UUID types in JDBC

### PR DESCRIPTION
**Pull request by pmlopes**
Fixes vert-x3/vertx-sql-common#19

Implemented a optimistic cast for JDBC types for now it decodes, temporal types plus UUID

### CODE REVIEW

**Comment by Narigo** [comment]
Would it make sense to add tests for the time / datetime etc. optimistic casts as well?

**Comment by pmlopes** [comment]
The old tests were already checking dates but using plain strings, the new code will return a proper type.

**Comment by pmlopes** [comment]
@cescoffier @vietj ready for review

**Comment by vietj** [comment]
I don't understand because I see stuff about datetime and not UUID in the commits

**Comment by vietj** [comment]
👍

**Pull request merged**
