### PR TITLE
Implement callable statements

### PR DESCRIPTION
**Pull request by pmlopes**
Relates to: https://github.com/vert-x3/vertx-sql-common/issues/5

Implement the JDBC stored procedure support. The implementation supports:

* calling functions (functions return results as part of the return keyword)
* calling "void" procedures (only input arguments)
* calling procedures that return results using the arguments (IN/OUT parameter)

### CODE REVIEW

**Comment by cescoffier** [comment]
looks good.

**Comment by cescoffier** [comment]
Documentation would be nice.

**Comment by pmlopes** [comment]
I'll document everything on sql-common since it is where the public API is and will be used by this and potentially by the async drivers too

**Comment by cescoffier** [comment]
As documentation has been provided, :+1:

**Pull request merged**
