### PR TITLE
Update JDBCStatementHelper.java

### PR DESCRIPTION
**Pull request by fiorenzino**
To be subclassed!

### CODE REVIEW

**Comment by tsegismont** [comment]
For which purpose? This is internal to Vert.x and it may disappear in any
version.

2017-05-07 14:17 GMT+02:00 fiorenzo pizza <notifications@github.com>:

**Comment by fiorenzino** [comment]
This is linked to permit a possibile extension:
https://github.com/vert-x3/vertx-jdbc-client/pull/100#issuecomment-299692878

**Comment by pmlopes** [comment]
As @tsegismont  said this would break the agreement on internal/public API, however if there are real use cases to access the code provided by this class we should propose to promote it from internal to public and assess what are the pros and cons or if we need to expose everything or not.

**Comment by fiorenzino** [comment]
Hi @pmlopes @tsegismont @vietj i started a little project to avoid the extension of your internal classes. I would like to following the vertx-jdbc style of coding, but i think i should replicate your internal code:
JDBCClient => JDBCClientImpl that share a JDBCConnectionImpl
[JDBCConnectionImpl implements SQLConnection]

I created a dirty copy of your SQLConnection (SimpleSQLConnection), with my 3 methods (persist, merge,delete) and :
SimpleJDBCClient => SimpleJDBCClientImpl => SimpleJDBCConnectionImpl
[where SimpleJDBCConnectionImpl implements SimpleSQLConnection]
At least:
JDBCPersist, JDBCMerge, JDBCDelete

Can you suggest a different strategy to preserve your code, without replicate all things?

I will share the code (i'm out of city, for vacancy).

**Comment by tsegismont** [comment]
Closing out of date

**Pull request closed without merging**
