### PR TITLE
Direct execution fix

### LINKED ISSUE #164: queryWithParams can not use all connection in the pool
### Version

* vert.x core: `3.7.1`
* vert.x jdbc-client: `3.7.1`
* jdbc driver: `6.0.6`
* RDBMS: `mysql server`

### General info

* What is your jdbc driver: `mysql-connector-java`
* What is your RDBMS server: `mysql`
* What is your connection string (no user/passwords please!): j`dbc:mysql://127.0.0.1:3306/db _dev?autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=UTC`

### Context

I execute a query to the db, and there is two different way that i use jdbc-client and produce two performance result that should be the same.

- create pool
```java
HikariConfig config = new HikariConfig();
    config.setDriverClassName(mySQLConfig.getDriver());
    config.setJdbcUrl(mySQLConfig.getUrl());
    config.setUsername(mySQLConfig.getUser());
    config.setPassword(mySQLConfig.getPassword());
    config.setMaximumPoolSize(mySQLConfig.getPoolSize());
    config.setAutoCommit(isAutoCommit);
    config.addDataSourceProperty("useServerPrepStmts", "" + mySQLConfig.isUseServerPrepStmts());
    config.addDataSourceProperty("cachePrepStmts", "" + mySQLConfig.isCachePrepStmts());
    config.addDataSourceProperty("prepStmtCacheSize", "" + mySQLConfig.getPrepStmtCacheSize());
    config.addDataSourceProperty(
        "prepStmtCacheSqlLimit", "" + mySQLConfig.getPrepStmtCacheSqlLimit());
    config.addDataSourceProperty("maxLifetime", "" + mySQLConfig.getMaxLifetimeMillis());

    try {
      logger.info("Connecting to datasource={}", JsonProtoUtils.printGson(mySQLConfig));
      DataSource dataSource = new HikariDataSource(config);

      mySQLClient = JDBCClient.create(vertx, dataSource);
      if (mySQLClient == null) {
        throw new Exception("mySQLClient == null");
      }
    } catch (Exception e) {
      future.fail(e);
      return future;
    }
```

- method 1: query using getConnection
```java
mySQLClient.getConnection(
          resConnection -> {
            if (resConnection.failed()) {
              result.fail(resConnection.cause());
              return;
            }

            SQLConnection connection = resConnection.result();
            connection.queryWithParams(
                prepareStm,
                params,
                selectRes -> {
                  if (selectRes.failed()) {
                    accountFuture.fail(selectRes.cause());
                  } else {
                    getResult(selectRes.result());
                  }
                  connection.close();
                });
          });
```

- method 2: query using SQLClient.queryWithParams
```java
mySQLClient
        .queryWithParams(prepareStm, params, asyncResultHandler);
```
- and there is result of prometheus metric when i run a benchmark, with connection pool config is 20:
  * method 1: vertx_pool_inUse{pool_type="datasource"}: 20
  * method 2: vertx_pool_inUse{pool_type="datasource"}: 1

and of course, method 1 has req/s much higher than method 2.

I see that both methods above use the  same method
```java
// class JDBCClientImpl
public SQLClient getConnection(Handler<AsyncResult<SQLConnection>> handler) {
    Context ctx = this.vertx.getOrCreateContext();
    this.getConnection(ctx, (ar) -> {
      ctx.runOnContext((v) -> {
        handler.handle(ar);
      });
    });
    return this;
  }
```

then why it makes a huge difference?

### PR DESCRIPTION
**Pull request by pendula95**
Fixes #164 
As mentioned direct command exection on JDBCClient is executed on main thread and to passed to worker threads.
Wrapped calls around JDBCConnection method that was added to execute abstract command via executeBlocking.

### CODE REVIEW

**Comment by angelsanzn** [comment]
It looks like something's messed with the git branches. 

I believe that, given that it's a single commit with few changes, if you can re-apply it to the latest master and ensure this PR includes only that single commit, it will increase the chances that this gets merged.

**Comment by pendula95** [comment]
I just noticed that this was fixed on master branch but never made it to release
https://github.com/vert-x3/vertx-jdbc-client/commit/b49a83ab48f3e58da4fbd5057074f860270f3e01
Complete rewrite was done. @pmlopes may have more info

**Comment by angelsanzn** [comment]
That's weird, as version 3.9.2 of vertx-jdbc-client was published to Maven Central [last July](https://mvnrepository.com/artifact/io.vertx/vertx-jdbc-client/3.9.2), months after that commit landed on master of this git repository.

However, as you indicate, that commit does not seem to make it into that release: https://github.com/vert-x3/vertx-jdbc-client/commits/3.9.2.

Pinging @vietj too as he merged #178, which introduced such commit. Does that actually fix #164, making this PR redundant? Discussion on that issue only a month ago suggested otherwise.

**Comment by pendula95** [comment]
I can confirm that https://github.com/vert-x3/vertx-jdbc-client/commit/b49a83ab48f3e58da4fbd5057074f860270f3e01 was not included 3.9.3 and the issue exists in this version also

**Comment by vietj** [comment]
@pendula95 can you provide a clean PR with only the fix you are proposing ? the current PR has many polluting commits and it is not possible to review it

**Comment by pendula95** [comment]
Can you please guide me how to provide clean PR in this case? Which head to take. As mention before commit #178 resolves this issue and is in master branch but this commit was not included in 3.9.2 or 3.9.3 release. For this PR I have checked out tag 3.9.2 and made single commit on 2 files.

**Comment by vietj** [comment]
@pendula95 just create a new branch from latest branch and use git cherry-pick to get the commits

**Comment by vietj** [comment]
the PR as is, is impossible to review

**Comment by angelsanzn** [comment]
@vietj From latest `master`?

**Comment by tsegismont** [comment]
Closing, superseded by #213

**Pull request closed without merging**
