### PR TITLE
Implement batching

### PR DESCRIPTION
**Pull request by pmlopes**
see: vert-x3/vertx-sql-common#22

Implemented batching support for jdbc clients (tests included)

Depends vert-x3/vertx-sql-common#22

### CODE REVIEW

**Comment by vietj** [comment]
in this documented ?

**Comment by pmlopes** [comment]
Documentation is on sql-common since the interfaces are defined there

**Comment by vietj** [comment]
I think we should test what happens when one of the statement in the batch fails and how the user can determine which statement failed.

**Comment by pmlopes** [comment]
You'll get a SQL exception as it happens in the JDBC API, batching is implemented at the driver level not on our code.

**Comment by vietj** [comment]
ok, thanks for the info

**Pull request merged**
