### PR TITLE
JDBC Named parameters

### PR DESCRIPTION
**Pull request by ckaminski**
Coupled with a pull request in vertx-sql-common, implements named parameters in the style of ':tagname".  I believe this accounts for all combinations of field delimiters (white-space,commas and parens), and also repetitive usage.

### CODE REVIEW

**Comment by pmlopes** [comment]
@ckaminski I think you have a problem with your regex, look for example at casting in postgres, say you want a column or even a variable to be casted to integer, you would do:

```sql
SELECT column::INTEGER FROM table WHERE other_column = :variable::VARCHAR
```

In this case your regex will fail...

**Comment by ckaminski** [comment]
I'm not attached to the :name parameter mapping.  It was something I was familiar with in other tools.  If you have a recommendation for something better?   ?name was something I had tried early on.

**Comment by ckaminski** [comment]
Updated to use ? instead of  : for parameter start.

**Comment by pmlopes** [comment]
the regex does not catch for example single character variables say:

```sql
select * from power_of_two where value = ?a
```

**Comment by pmlopes** [comment]
personally i'd prefer either `:variable_name` or `@variable_name` the question mark feels a bit strange since i tend to associate it with a variable to be replaced as with jdbc.

**Comment by ckaminski** [comment]
So I've been playing around with the regex and taken your input into account.  The following is some experimentation.  If you think this is a good direction, I'll probably re-base this to 3.1.0 and resubmit. 

https://regex101.com/r/oB2sA2/1

**Comment by electrotype** [comment]
Subscribed.

Maybe have a look at Spring's [NamedParameterUtils](https://github.com/spring-projects/spring-framework/blob/master/spring-jdbc/src/main/java/org/springframework/jdbc/core/namedparam/NamedParameterUtils.java) for inspiration?

**Comment by coding2012** [comment]
What about: ?:parametername would that be easier to detect via regex?
Just a thought. I wonder too if a small flag could be passed in the Json query / update that disables the named params feature...

**Comment by ensirius** [comment]
are this alive?

**Comment by ckaminski** [comment]
Sadly no;  this would need to be reworked quite a bit for current versions of Vertx.  I may revisit this in the future, but I'll close for now.

**Pull request closed without merging**
