### PR TITLE
Fixes #61: Implement a streaming API for results

### LINKED ISSUE #61: response should be a stream not a json blob
The current API returns always a single JSON blob with the response from the database. Although this is interesting for simplicity when dealing with a big response data set it will create lot of pressure on the JVM available heap and GC since all rows need to be fetched to RAM, encoded to JSON and sent over the eventbus.

An improvement would be having the concept of cursor where users can fetch one or many rows at once, or a streaming handler.

### PR DESCRIPTION
**Pull request by pmlopes**
Fixes #61 

Implementation of the proposal for streaming queries. The interface is quite simple due to the fact that it can be implemented using the JDBC driver as well the async driver.

Once the API discussions are complete we can work on the async driver support too.

### CODE REVIEW

**Comment by vietj** [comment]
I would like to see a test with RxJava and use the stream as an Observable

**Comment by pmlopes** [comment]
@vietj minimal RX test added

**Comment by vietj** [comment]
@pmlopes great

**Comment by vietj** [comment]
the impl looks good, however I'm wondering if we should not read a (configurable) batch of rows instead 1 row at a time

**Comment by pmlopes** [comment]
Yes I can loop a configurable amount of rows in one execute blocking instead of a single row for each execute blocking.

**Comment by jponge** [comment]
👍

**Pull request merged**
