### PR TITLE
Convert callable statement out parameter from ResultSet to JSON

### LINKED ISSUE #135: Exception when execute stored procedure with cursor output parameter
### Version

* vert.x core: 3.5.1
* vert.x jdbc-client: 3.5.1
* jdbc driver: oracle.jdbc.pool.OracleDataSource
* RDBMS: Oracle Database 12.2.0.1

### General info

* What is your jdbc driver: oracle.jdbc.pool.OracleDataSource
* What is your RDBMS server: Oracle Database 12.2.0.1
* What is your connection string (no user/passwords please!): `jdbc:oracle:thin:@//${host}:${port}/${service}`

### Context
I have a simple stored procedure like this:
```sql
CREATE OR REPLACE PROCEDURE TEST_OUT(p_out OUT SYS_REFCURSOR) IS
  BEGIN
    OPEN p_out FOR SELECT 'HELLO' FROM DUAL;
  END ;
```
Then I invoke from the JDBC Client
``` java
JsonArray out = new JsonArray().add(OracleTypes.CURSOR);
client.callWithParams("{call TEST_OUT(?)}", null, out, resultSetHandler -> {
            if (resultSetHandler.failed()) {
                resultSetHandler.cause().printStackTrace();
            }
        });
```
Output:
```
java.lang.IllegalStateException: Illegal type in JsonObject: class io.vertx.ext.sql.ResultSet
	at io.vertx.core.json.Json.checkAndCopy(Json.java:210)
	at io.vertx.core.json.JsonArray.add(JsonArray.java:439)
	at io.vertx.ext.jdbc.impl.actions.JDBCCallable.convertOutputs(JDBCCallable.java:100)
	at io.vertx.ext.jdbc.impl.actions.JDBCCallable.execute(JDBCCallable.java:80)
	at io.vertx.ext.jdbc.impl.actions.JDBCCallable.execute(JDBCCallable.java:31)
	at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.handle(AbstractJDBCAction.java:58)
	at io.vertx.ext.jdbc.impl.actions.AbstractJDBCAction.lambda$execute$0(AbstractJDBCAction.java:66)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```
### Solution
I looked at JDBCCallable and this statement: 
``` java
result.add(helper.asList((ResultSet)value));
``` 
will always throw exception since Json cannot accept value of type ResultSet.

As a quick fix, I changed it to: 
``` java
result.add(helper.asList((ResultSet) value).toJson());
```
The exception is gone and I can get the output by json processing, or reconstruct the ResultSet from json. But I think there's should be a better solution, can we take a look at that?

### PR DESCRIPTION
**Pull request by dat91**
Fixes #135

Fix exception when ResultSet return as out parameter

### CODE REVIEW

**Comment by vietj** [comment]
@dat91 can you add a test for the bug it fixes ?

**Comment by dat91** [comment]
@vietj It seems like this issue is very specific for Oracle DB. I tried with HSQLDB and H2 but cannot simulate the scenario. Is it make sense if I added a test that run on my local Oracle instance and marked it as Ignored?

**Comment by manikantag** [comment]
Yes. Me too got the same issue for Oracle. Otherwise working fine for MySQL, SQLServer, DB2.

But I've a doubt regarding the fix in this PR. Should we add `.toJson()` or `.getResults()` ?

I've added more details here: https://github.com/vert-x3/vertx-jdbc-client/issues/131#issuecomment-425867440

Using `.getResults()` will add `JsonArray` of values, and using `.toJson()` will add `JsonObject` of column names & values.

If we use `.toJson()`, then we need to get the actual data, like below:

```java
int dataCursorOutParamPosition = -1;
List<JsonObject> rows;

// For Oracle procedures, actual data comes via one of registered
// OUT param of type oracle.jdbc.OracleTypes.CURSOR
if (databaseType == DatabaseType.Oracle // App specific enum of all supported DB types.
        && outParams != null
        && !outParams.isEmpty()) {
    dataCursorOutParamPosition = outParams.getList()
                                          .indexOf(OracleTypes.CURSOR);
}

if (dataCursorOutParamPosition != -1) {
    // For Oracle, get data from OUT cursor instead of ResultSet.
    JsonArray rowsArray = (JsonArray) resultSet.getOutput()
                                               .getJsonObject(dataCursorOutParamPosition)
                                               .getMap()
                                               .get("rows");
    rows = rowsArray.getList();
} else {
    // For other databases, get data from ResultSet directly.
    rows = resultSet.getRows();
}
```

**My fix in `JDBCCallable.convertOutputs()`:**

```java
  private JsonArray convertOutputs(CallableStatement statement) throws SQLException {
    ...
    for (int i = 0; i < out.size(); i++) {
      ...
        if (value == null) {
          ...
        } else if (value instanceof ResultSet) {
          result.add(helper.asList((ResultSet) value).getResults()); // -----> adding rs.getResults() to result
        } else {
          ....
  }
```

Now, I've to do like below to get actual data:

```java
resultSet.getOutput()
         .getJsonArray(dataCursorOutParamPosition)
         .getList()
```

Is there any better, common way to achieve this?

**Comment by vietj** [comment]
I'm guessing that there are no oracle docker images ?

**Comment by Chlorek** [comment]
To my surprise there is [official oracle docker image here](https://github.com/oracle/docker-images/tree/master/OracleDatabase)
And I hope API decisions won't hold this patch for long, because it really is deal breaking feature when working with damn Oracle databases.

**Comment by vietj** [comment]
I merged it, I also created this issue https://github.com/vert-x3/vertx-jdbc-client/issues/173 for having a test for it using Docker. @dat91 can you provide such test using TestContainers ?

**Comment by dat91** [comment]
@vietj sure, I will try.

**Comment by vietj** [comment]
thanks waiting for your PR :-)

**Pull request merged**
