### PR TITLE
Modified JDBCClose to check whether the connection is closed before t…

### PR DESCRIPTION
**Pull request by lalitjeevanrao**
Modified JDBCClose to check whether the connection is closed before trying to call close() and metrics.end(). This handles sending negative value in vertx datsource pool metrics

Signed-off-by: Lalit Rao <lalit.rao@hopscotch.in>

### CODE REVIEW

**Comment by vietj** [comment]
why is this PR needed ?

**Comment by lalitjeevanrao** [comment]
Hi Julien,
That PR is against the issue I raised regarding negative value in
datasource pool metrics. I referred to contributors guide
<https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md> and figure
out how to resolve and contribute.

*Lalit Rao* | Technology
+91 8454 979 109
www.hopscotch.in
------------------------------
[image: Hopscotch] <https://www.hopscotch.in/>
Hopscotch Wholesale Trading Pvt. Ltd,
1st Floor, DGP House, Prabhadevi,
Mumbai - 400025, India

**Comment by vietj** [comment]
it has been fixed already in this project, thanks!

**Comment by lalitjeevanrao** [comment]
Alright Julien. Thanks.

**Pull request closed without merging**
